### ISSUE TITLE
Suggestion: Fork this repo for jdk8

### ISSUE THREAD

**Issue by parkiyong** [KaOS-Community-Packages/jdk#1]
Since jdk9 is consider stable, I would suggest to update this repo to jdk 9 and create another repo named jdk8 (fork from this current repo) to maintain jdk8 updates.

**Comment by fjmorazan** [comment]
Hi @wrajaka,
You can [apply for membership](https://kaosx.us/docs/kcp/) and get access to all PKGBUILDs in KCP so that you can update any PKGBUILD and [add your own package](https://kaosx.us/docs/kcp/#submitting-a-package) without the need for a PR. 😁

**Comment by Adurol** [comment]
Here are the ways I see what we could do:

1. Update `jdk` to Java 9.x, deprecate Java 8
1. Rename `jdk` to `jdk8` and create/update `jdk` with Java 9
1. Rename `jdk` to `jdk8` and create a new `jdk9` with Java 9

The problem I have is that for compatibility reasons we would need a `provides=("jdk")`. But which version should be `jdk`?

---

Personally, I'm in favor for 1.) as Java 8 will see it's EOL in [Sep 2018](http://www.oracle.com/technetwork/java/eol-135779.html). And before long, the versioning scheme will change for Java anyway...
